#!/usr/bin/env python3

import argparse


def main(cmd=None):
    parser = argparse.ArgumentParser(description='GRVTY Password Reset Build Tool')
    parser.add_argument('-t', '--distType', choices=['internal', 'external'], default='external',
                        help='environment to build for')
    parser.add_argument('-o', '--output', default='build', help='directory to output the built project to')
    kwargs = parser.parse_args(cmd)
    print('Starting build process')

if __name__ == '__main__':
    main()
